export const filterData = {
  male: "gender",
  female: "gender",
  "O-": "bloodGroup",
  "B+": "bloodGroup",
  "AB+": "bloodGroup",
  "AB-": "bloodGroup",
  "A-": "bloodGroup",
  "B-": "bloodGroup",
  "A+": "bloodGroup",
  "O+": "bloodGroup",
  "University of Wisconsin--Madison": "university",
  "Ohio State University": "university",
  "Pepperdine University": "university",
  "University of Southern California": "university",
  "Northeastern University": "university",
  "University of North Carolina--Chapel Hill": "university",
  "University of Illinois--Urbana-Champaign": "university",
  "Syracuse University": "university",
  "California Institute of Technology (Caltech)": "university",
  "William & Mary": "university",
  "New York University (NYU)": "university",
  "Tufts University": "university",
  "Harvard University": "university",
  "Washington University in St. Louis": "university",
  "University of Pennsylvania": "university",
  "Georgetown University": "university",
  "Columbia University": "university",
  "Boston College": "university",
  "Johns Hopkins University": "university",
};
